name: 'Composite hello world'
description: 'A composite actions that sais hello to a user'

inputs:
  person:
    description: "Who should be greeted?"
    required: true
    default: 'World'

outputs:
  time:
    description: 'The time the person was greeted.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.person }}
